### ISSUE TITLE
Source of smpl_numpy.py

### ISSUE THREAD

**Issue by greatbaozi001** [GAP-LAB-CUHK-SZ/MVHumanNet#11]
hello, thanks for your great work. I am curious of the source of `smpl_numpy.py`, as it seems is a script form third parties, can you provide some information about where did you access the code? thanks.

**Comment by greatbaozi001** [comment]
the file metioned above is locate at [smpl_numpy.py](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/blob/main/visual_smpl/smpl_/smpl_numpy.py). the earliest version of this file i can find is locate at [humannerf](https://github.com/chungyiweng/humannerf/blob/main/third_parties/smpl/smpl_numpy.py)

**Comment by JesseLiao00** [comment]
Hi, @greatbaozi001. This script possibly comes from the official smplx codebase and is modified by other works. You can check https://github.com/vchoutas/smplx/blob/main/smplx/body_models.py

**Comment by greatbaozi001** [comment]
thanks for your reply!
