### ISSUE TITLE
Questions about camera extrinsics

### ISSUE THREAD

**Issue by Langwenchong** [GAP-LAB-CUHK-SZ/MVHumanNet#14]
Hello,

First of all, thank you very much for making this dataset open-source. However, I have some questions regarding the camera parameters. In the provided camera_extrinsics.json, I took the rotation and translation matrices and concatenated them into a 4x4 homogeneous matrix to form the camera extrinsics. Is this camera extrinsic in the camera-to-world format or the world-to-camera format? Additionally, what are the directions of the x, y, and z axes? Are they in the OpenGL format (x points to the right, y points up, and z points backward relative to the image view direction) or in the OpenCV format (x points to the right, y points down, and z points forward relative to the image view direction)? This information is crucial for my MVS-based reconstruction project. Looking forward to your prompt response!

Best regards.

**Comment by JesseLiao00** [comment]
Hi, the camera extrinsic is in world-to-camera, OpenCV format. Please note that the translation should be multiplied by a camera scale(from camera_scale.pkl). Then the extrinsic and intrinsic should be correct.
