### ISSUE TITLE
Frameratre for original and released data. 25 or 30 fps? 

### ISSUE THREAD

**Issue by zehongs** [GAP-LAB-CUHK-SZ/MVHumanNet#15]
Hi @X-zhangyang @kevinlee09 , Thanks for the great work. I'm wondering if it is convenient to clarify the framerate of the released data? It looks like around 10fps instead of the 25fps (in main paper) or 30fps (in supplementary).

**Comment by JesseLiao00** [comment]
Hi, @zehongs. The original FPS of the videos is 30 or 25. However, we only keep one frame out of every 5 frames(e.g. 0005.jpg, 0010.jpg, 0015.jpg,...) for further processing due to storage concerns. The resulting FPS of released data should be 6 or 5.
