### ISSUE TITLE
get error when running download_tool_mvhuman.py

### ISSUE THREAD

**Issue by qiaoling123455** [GAP-LAB-CUHK-SZ/MVHumanNet#18]
I have filled the form and get right url, and can download data through browser.  but when I run 
download_tool_mvhuman.py, wrong happened
-------------------------------------------------
i:  sites
i:  SSE_GAP-Lab
i:  Documents
i:  MVHumanNet_Part_01
graphqlReq {'data': {'legacy': {'renderListDataAsStream': None}, 'perf': {'executionTime': 16.397000000000002, 'overheadTime': 9.8238, 'parsingTime': 0.051199999999999996, 'queryCount': 3, 'validationTime': 0.4827, 'resolvers': [{'name': 'Mondo', 'queryCount': 2, 'resolveTime': 11.7194, 'waitTime': 0.6044}, {'name': 'RenderListDataAsStream', 'queryCount': 1, 'resolveTime': 3.7485, 'waitTime': 13.0138}]}}, 'errors': [{'message': 'Item not found', 'extensions': {'code': 'itemNotFound'}}, {'message': 'Item not found', 'locations': [{'line': 8, 'column': 7}], 'path': ['legacy', 'renderListDataAsStream'], 'extensions': {'code': 'itemNotFound'}}]}

Traceback (most recent call last):
  File "/home/Dataset/MVHumanNet/download_tool_mvhuman.py", line 275, in <module>
    getFiles(args.url, download_folder , force )
  File "/home/Dataset/MVHumanNet/download_tool_mvhuman.py", line 207, in getFiles
    if "NextHref" in graphqlReq["data"]["legacy"]["renderListDataAsStream"]["ListData"]:

**Comment by JesseLiao00** [comment]
Hi, @qiaoling123455.
Actually, we haven't encountered this error yet. Do you also get this error when rerunning this script or trying another network environment?
