### ISSUE TITLE
Camera ID and specific location are irrelevant？

### ISSUE THREAD

**Issue by dodododddo** [GAP-LAB-CUHK-SZ/MVHumanNet#21]
Could you provide the IDs of the surround-view cameras at the same height (or with no pitch angle difference)?

**Comment by JesseLiao00** [comment]
Hi, @dodododddo.
For 48view, <html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cuhksz/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cuhksz/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">


row1 | row2 | row3
-- | -- | --
CC32871A020 | CC32871A044 | CC32871A046
CC32871A056 | CC32871A031 | CC32871A010
CC32871A009 | CC32871A055 | CC32871A040
CC32871A014 | CC32871A029 | CC32871A037
CC32871A043 | CC32871A005 | CC32871A035
CC32871A018 | CC32871A033 | CC32871A016
CC32871A012 | CC32871A050 | CC32871A030
CC32871A021 | CC32871A059 | CC32871A038
CC32871A060 | CC32871A017 | CC32871A023
CC32871A006 | CC32871A034 | CC32871A027
CC32871A042 | CC32871A032 | CC32871A051
CC32871A041 | CC32871A052 | CC32871A015
CC32871A049 | CC32871A039 | CC32871A022
CC32871A036 | CC32871A058 | CC32871A057
CC32871A047 | CC32871A013 | CC32871A048
CC32871A019 | CC32871A004 | CC32871A008



</body>

</html>

And for the 24/16view setting, ["22327091", "22327084", "22327107", "22236229", "22327073", "22236234", "22327109", "22236222", "22236236", "22327111", "22327118", "22327117", "22327116", "22236235", "22327102", "22327113"] is on the same height.

Best.

**Comment by dodododddo** [comment]
Thx!
