### ISSUE TITLE
camera 41 looks different on 2 subjects

### ISSUE THREAD

**Issue by xiyichen** [GAP-LAB-CUHK-SZ/MVHumanNet#23]
Hi, thanks for releasing the dataset.
I found that there's a problem with the extrinsic parameters of camera 41. Below are the images of 2 subjects captured with that camera.
![0580_img_100050](https://github.com/user-attachments/assets/9353d365-16e2-4788-a331-1c9b94c79318)
![0580_img_100080](https://github.com/user-attachments/assets/447be816-9b6c-46e5-9005-c59837faf597)
You can see the background lights seem to be shifted and rotated slightly.

If I project smpl vertices to 2d using this camera, there's a misalignment for the second subject.
![41_projections_100050](https://github.com/user-attachments/assets/3811e560-3a1c-4552-ae6c-262d091c32c4)
![41_projections_100080](https://github.com/user-attachments/assets/d29e31cb-4593-406e-98d7-b1d96c6cfad8)

It seems to me that camera 41 does not always have the same extrinsics matrix for every subject, but in your provided extrinsic parameters, they are always the same. Could you confirm this and update the correct extrinsics?

I visualized all the other cameras and they all look good.

**Comment by xiyichen** [comment]
I think the misalignment mainly comes from the camera translation. I optimized the translation using loss between gt and smpl joints for one frame and got 

> [-0.2544,  0.7561,  2.7962]

which seems more accurate for subjects starting from 100066, but if you know the gt camera translation for these subjects, I would appreciate that you could release them.

**Comment by xiyichen** [comment]
![debug](https://github.com/user-attachments/assets/51a1f831-dc42-4cde-9366-f4174e2c8854)
However, I also found that the smpl parameters aren't accurate for some frames. Did you perform further optimization using smpl joints and 2d joints from all 48 cameras to optimize for the smpl/smplx parameters, similar to smplify-x but in a multi-camera setup?

**Comment by JesseLiao00** [comment]
> Hi, thanks for releasing the dataset. I found that there's a problem with the extrinsic parameters of camera 41. Below are the images of 2 subjects captured with that camera. ![0580_img_100050](https://private-user-images.githubusercontent.com/50854238/381307760-9353d365-16e2-4788-a331-1c9b94c79318.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTQxNzYsIm5iZiI6MTczMDY5Mzg3NiwicGF0aCI6Ii81MDg1NDIzOC8zODEzMDc3NjAtOTM1M2QzNjUtMTZlMi00Nzg4LWEzMzEtMWM5Yjk0Yzc5MzE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxYTA1OTk2YzIzNTJlOTc4ODY4YzY4OWJiMjMxNWZiOTBjOTUyMzM3ODk2NTM0NmY3ZGRmMTRhZmE2MjI4ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9OBGqbQAdqQQrNHW-XbE6SLnMgvLQkG5yRCvypS1BMM) ![0580_img_100080](https://private-user-images.githubusercontent.com/50854238/381307762-447be816-9b6c-46e5-9005-c59837faf597.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTQxNzYsIm5iZiI6MTczMDY5Mzg3NiwicGF0aCI6Ii81MDg1NDIzOC8zODEzMDc3NjItNDQ3YmU4MTYtOWI2Yy00NmU1LTkwMDUtYzU5ODM3ZmFmNTk3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwM2IwNTMzODkzZmJmMGU1ODk4YzFhMTdkYTE4YzY4N2JmYTcyZWZlYjRjMTljYmE5ODcwNzI3ODI5MTYzNmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rofNah2NJn1qDTwWk0t0rK6mCfRXBaV9zcALlltTkCc) You can see the background lights seem to be shifted and rotated slightly.
> 
> If I project smpl vertices to 2d using this camera, there's a misalignment for the second subject. ![41_projections_100050](https://private-user-images.githubusercontent.com/50854238/381308075-3811e560-3a1c-4552-ae6c-262d091c32c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTQxNzYsIm5iZiI6MTczMDY5Mzg3NiwicGF0aCI6Ii81MDg1NDIzOC8zODEzMDgwNzUtMzgxMWU1NjAtM2ExYy00NTUyLWFlNmMtMjYyZDA5MWMzMmM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2E2ZmNkYzRlODg5MmZiM2ZhMGM4MzYwNDkxNTBmYzI3MWU0NWUyNDdlMzIxZTFiYjI4YzRmMTBmZDUzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.QSHqrCPWhKZvDyWdT2P_UwB8twiirn2ryTad3eXyKLQ) ![41_projections_100080](https://private-user-images.githubusercontent.com/50854238/381308086-d29e31cb-4593-406e-98d7-b1d96c6cfad8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2OTQxNzYsIm5iZiI6MTczMDY5Mzg3NiwicGF0aCI6Ii81MDg1NDIzOC8zODEzMDgwODYtZDI5ZTMxY2ItNDU5My00MDZlLTk4ZDctYjFkOTZjNmNmYWQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDA0MTc1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZDgxYmVlMGZjZTU4NTdmYTY0YTNiZWZjMzM0Y2M2YzFmZDhjNzIyOWNmYWM1MGViMzgwYmJmZWI2ZTUyOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.C9NAZ_X0EfSFJIiplnxSdX2fRut8h89W4TQ0_ld3ktg)
> 
> It seems to me that camera 41 does not always have the same extrinsics matrix for every subject, but in your provided extrinsic parameters, they are always the same. Could you confirm this and update the correct extrinsics?
> 
> I visualized all the other cameras and they all look good.


@xiyichen Hi, xiyi. Camera 41 is different from different subjects may be due to a possible collision(which leads to camera rotations). Because we collected many subjects in a day, we couldn't update the extrinsic for each ID while updating every one or two days. I suggest that you could skip this ID and near-round ones and try other IDs.

**Comment by JesseLiao00** [comment]
Regarding https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/issues/23#issuecomment-2445440985, our current SMPLX/estimations are using Easymocap(https://github.com/zju3dv/EasyMocap.git) which already uses multi-camera setup. Accurate SMPLX estimation remains challenging so far. Unfortunately, re-running the SMPLX fitting for all IDs with a different tool for us is not feasible due to time and resource constraints. We apologize for this and recommend using other IDs that provide more accurate SMPLX estimations.

**Comment by xiyichen** [comment]
thanks for your response!
