### ISSUE TITLE
Intrinsics matrix of each camera

### ISSUE THREAD

**Issue by KhanhNgoDuy** [GAP-LAB-CUHK-SZ/MVHumanNet#24]
Hi, I have downloaded part 2 of MVHuman dataset. For each subject (e.g. 201000), I found that there is only 1 camera intrinsics, saved in `camera_intrinsics.json`. Does this mean all cameras from 16 views share the same intrinsics parameters?

**Comment by JesseLiao00** [comment]
Hi, @KhanhNgoDuy. Yes, all cameras in one subject share the same intrinsic parameters.
