### ISSUE TITLE
How to visualize smpl on image plane？

### ISSUE THREAD

**Issue by GuGuDaDaDa** [GAP-LAB-CUHK-SZ/MVHumanNet#3]
Thank you for your great work!  Could you provide some demo for projecting vertices generated by smplx parameters? Thank you.

**Comment by X-zhangyang** [comment]
We have uploaded the relevant script to visualize smplx on image plane.

See https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/tree/main/visual_smpl.
