### ISSUE TITLE
Have the images been distortion corrected?

### ISSUE THREAD

**Issue by wenkaier** [GAP-LAB-CUHK-SZ/MVHumanNet#4]
"dist": []   in camera_intrinsics.json

**Comment by X-zhangyang** [comment]
You can try to visualize smpl on image plane with released code.
Refer to https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/tree/main/visual_smpl

**Comment by JesseLiao00** [comment]
Our calibration procedure didn't involve image distortion, so the distortion parameters are None. According to our experiments, there are no noticeable impacts. @wenkaier
