### ISSUE TITLE
sample 101688 Missing data

### ISSUE THREAD

**Issue by wenkaier** [GAP-LAB-CUHK-SZ/MVHumanNet#5]
![1](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/assets/152501403/42d4140b-7a13-4b69-98a7-a6a2b33fb15f)

**Comment by X-zhangyang** [comment]
We checked the data and did not find similar issues. 
Try to download this file again.
![image](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/assets/33534662/851b2586-7d06-4d65-a6f6-828594b5a5e7)
