### ISSUE TITLE
I wonder how to calculate the focal length in millimeters and what camera_scale means?

### ISSUE THREAD

**Issue by Dcvu233** [GAP-LAB-CUHK-SZ/MVHumanNet#6]

**Comment by JesseLiao00** [comment]
Hi, for camera_scale, please refer to #14. And focal length can be obtained from the intrinsic file(camera_intrinsics.json)

**Comment by rorrewang** [comment]
Hi,could you please tell me how do you get the camera_scale data ?Is it generated from easymocap ?

**Comment by JesseLiao00** [comment]
> Hi @JesseLiao00 , could you please tell me how do you get the camera_scale data ?Is it generated from easymocap ?

Hi, @rorrewang. As mentioned in our paper, we used a commercial solution based on CharuCo boards to calibrate the cameras. Parameter `camera_scale` is related to the CharuCo board size and multipling it to `T` contributes to correct extrinsic matrix.

**Comment by rorrewang** [comment]
@JesseLiao00  I understand . Thanks!
