### ISSUE TITLE
Command Line Download

### ISSUE THREAD

**Issue by Lewis-lv0** [GAP-LAB-CUHK-SZ/MVHumanNet#8]
Hi @X-zhangyang , thanks for your great work! I would like to ask if there is a command line scipt to download the dataset as I found downloading from the web browser often suffers from unexpected interruptions, especially for those very large files.

**Comment by X-zhangyang** [comment]
Thank you for your interest in our dataset.  
We have provided the [script](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/blob/main/download_tool_mvhuman.py) to downloand the dataset.  Before using it, please make sure you have filled out our form and obtained the download links.

**Comment by Lewis-lv0** [comment]
Thanks you for your efforts! That would be very useful. Closing this issue..
