### ISSUE TITLE
Downloading issues

### ISSUE THREAD

**Issue by antonzub99** [GAP-LAB-CUHK-SZ/MVHumanNet#9]
Many thanks for releasing such a crazy amount of high-quality data! It is truly impressive and will be super important for Vision and Graphics research!

However, I'd like to ask for some help with downloading:
* It appears that the configuration of the OneDrive with data doesn't allow downloading multiple files at the same time - it throws this error;
```
This file cannot be downloaded. 

ExceptionType: AccessExpiredMeTAException. 
```
* It is possible though to download each part of the dataset as a single ~3 TB archive, which is a lot of data for a single downloading process and will probably fail eventually;
* I didn't manage to use Azure AD utilities and REST API to download the data from public links using a Python script;
* It also seems impossible to parse download links for individual archives in a folder as these links are unavailable, making it impossible for REST API-based downloading.

So it would be extremely helpful to enable individual download links for each `.tar.gz` archive in data folders and make them also available for parsing. I would be very happy to try if there are any other suggestions on making dataset downloading feasible!

Thank you again for the release!

**Comment by X-zhangyang** [comment]
Thank you for your interest in our dataset.  
We have provided the [script](https://github.com/GAP-LAB-CUHK-SZ/MVHumanNet/blob/main/download_tool_mvhuman.py) to downloand the dataset.

**Comment by antonzub99** [comment]
Thank you, this script is extremely helpful!
